config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
               registrations: "registrations"
             }

  resources :courses do
    member do
      post :inscribe
    end
  end

  resources :inscriptions do
    resources :sections, only: [:show, :update] do
      resources :activities, only: [:update]
    end
  end

  get 'edit_user', to: 'users#edit'
  put 'update_user', to: 'users#update'
  get 'my_classroom', to: 'my_classroom#index'
  get 'my_courses', to: 'my_courses#index'

  root to: 'home#index'
end

app/controllers/my_classroom_controller.rb
class MyClassroomController < ApplicationController
  def index
    authorize :my_classroom, :index?
  end
end

app/views/my_classroom/index.html.erb
<div>
  <div class="myclassroom__header">
    <div class="container">
      <div class="row">
        <div class="col-3 text-center">
          <div class="myclassroom__profile-pic">
            <%= image_tag current_user.avatar.url, class:"myclassroom__profile-pic-img" %>
          </div>
        </div>

        <div class="col-4">
          <div class="myclassroom__stats">
            <div class="mono-title">
              My Classroom
            </div>
            <div class="main-title">
              <%= current_user.name %>
            </div>
            <div class="badge">
              <div class="image">
                <%= badge_image_for current_user %>
              </div>
              <div class="title">
                <%= badge_title_for current_user %>
              </div>
            </div>
            <div class="completed-courses">
              <%= current_user.inscriptions.completed.count %> COURSES COMPLETED
            </div>
            <div class="badge flex-column">
              <div class="bar">
                <div class="progress" style="width:<%= student_progress_percentage current_user %>%;"></div>
              </div>
              <div class="points">
                <%= student_progress current_user %> FOR NEXT RANK
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="myclassroom__activity">
    <div class="container">
      <div class="row">
        <div class="myclassroom__activity-active">
          <div class="main-title">
            My active courses
          </div>
          <div>
            <% current_user.inscriptions.in_progress.in_groups_of(3, false) do |group| %>
              <div class="row">
                <% group.each do |in_progress_inscription| %>
                  <div class="col-4">
                    <div class="myclassroom__course">
                      <div class="align vertical">
                        <%= link_to inscription_path in_progress_inscription do %>
                          <div class="main-subtitle">
                            <%= in_progress_inscription.course.name %>
                          </div>
                          <div class="mono-subtitle__alt">
                            <%= in_progress_inscription.progress.completed_sections %> / <%= in_progress_inscription.progress.total_sections %> Modules
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="myclassroom__activity-past">
          <div class="main-title">
            My completed courses
          </div>
          <div>
            <% current_user.inscriptions.completed.in_groups_of(3, false) do |group| %>
              <div class="row">
                <% group.each do |completed_inscription| %>
                  <div class="col-4">
                    <div class="myclassroom__course">
                      <div class="align vertical">
                        <div class="main-subtitle">
                          <%= completed_inscription.course.name %>
                        </div>
                        <div class="mono-subtitle__alt">
                          <%= completed_inscription.progress.total_sections %> Modules
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>