config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
               registrations: "registrations"
             }

  resources :courses do
    member do
      post :inscribe
    end
  end

  resources :inscriptions do
    resources :sections, only: [:show, :update] do
      resources :activities, only: [:update]
    end
  end

  get 'edit_user', to: 'users#edit'
  put 'update_user', to: 'users#update'
  get 'my_classroom', to: 'my_classroom#index'
  get 'my_courses', to: 'my_courses#index'

  root to: 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  has_many :inscriptions, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :points
  has_many :levels
  has_many :badges, through: :levels

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/user_placeholder.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  attr_accessor :role

  def set_role(role)
    role = if role.present?
             role.to_sym
           else
             :student
           end
    add_role role
  end

  def inscribed?(course)
    inscriptions.where(course_id: course.id).present?
  end

  def inscription_for(course)
    inscriptions.find_by(course_id: course.id)
  end

  def pontuation(kind_name)
    kind_id = Kind.find_by(name: kind_name)
    points.where(kind_id: kind_id).sum(:value)
  end

  def change_points(options)
    if Gioco::Core::KINDS
      points = options[:points]
      kind   = Kind.find(options[:kind])
    else
      points = options
      kind   = false
    end

    if Gioco::Core::KINDS
      raise "Missing Kind Identifier argument" if !kind
      old_pontuation = self.points.where(kind_id: kind.id).sum(:value)
    else
      old_pontuation = self.points.to_i
    end
    new_pontuation = old_pontuation + points
    Gioco::Core.sync_resource_by_points(self, new_pontuation, kind)
  end

  def next_badge?(kind_name = false)
    old_pontuation = pontuation(kind_name)

    next_badge       = Badge.where("points > #{old_pontuation}").order("points ASC").first

    if next_badge
      {
        badge: next_badge,
        points: next_badge.points - old_pontuation,
        next_badge_points: next_badge.points
      }
    else
      {
        badge: "",
        points: 0,
        next_badge_points: 0
      }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def edit; end

  def update
    if params[:password]&.empty?
      if current_user.update_without_password(user_params)
        redirect_to root_path
      else
        redirect_to edit_user_path
      end
    else
      if current_user.update_attributes(user_params)
        redirect_to root_path
      else
        redirect_to edit_user_path
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :name, :you_do, :password, :password_confirmation)
  end
end

app/views/users/edit.html.erb
<div class="registration-container">
  <div class="align vertical">
    <%= form_for(current_user, as: "user", url: update_user_path, html: { multipart: true, method: :put } ) do |f| %>
      <div class="field">
        <%= f.file_field :avatar %>
      </div>

      <div class="field">
        <%= f.label :name, class: 'registration-container__label' %><br />
        <%= f.text_field :name, autofocus: true, placeholder: "Name", class: 'registration-container__input' %>
      </div>

      <div class="field">
        <%= f.label :password, class: 'registration-container__label' %><br />
        <%= f.password_field :password, autocomplete: "off", placeholder: "Password", class: 'registration-container__input' %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation, class: 'registration-container__label' %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Confirm Password", class: 'registration-container__input' %>
      </div>

      <div class="field">
        <%= f.label :you_do, class: 'registration-container__label' %><br />
        <%= f.text_field :you_do, placeholder: "What do you do?", class: 'registration-container__input' %>
      </div>

      <div class="actions">
        <%= f.submit "Update", class: 'button-std' %>
      </div>
    <% end %>
  </div>
</div>