config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
               registrations: "registrations"
             }

  resources :courses do
    member do
      post :inscribe
    end
  end

  resources :inscriptions do
    resources :sections, only: [:show, :update] do
      resources :activities, only: [:update]
    end
  end

  get 'edit_user', to: 'users#edit'
  put 'update_user', to: 'users#update'
  get 'my_classroom', to: 'my_classroom#index'
  get 'my_courses', to: 'my_courses#index'

  root to: 'home#index'
end

app/models/inscription.rb
class Inscription < ApplicationRecord
  include Editable

  belongs_to :course
  belongs_to :user

  enum status: %i[in_progress completed]
  delegate :name, :description, :objectives, prefix: true, to: :course

  def owner?(owner)
    user.id == owner.id
  end

  def progress
    SectionManager.progress sections
  end

  def all_sections_completed?
    sections.select { |_section_id, section| section["completed"] && section["completed"] }.count == sections.count
  end
end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController
  before_action :set_inscription, only: %i[show edit update destroy]

  def index
    authorize Inscription
    @inscriptions = current_user.inscriptions
  end

  def show
    authorize @inscription
  end

  def edit
    authorize @inscription

    redirect_to SectionManager.continue(@inscription) || @inscription
  end

  def update
    authorize @inscription

    if @inscription.update(inscription_params)
      redirect_to @inscription, notice: "Inscription was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    authorize @inscription

    if @inscription.destroy
      redirect_to inscriptions_url, notice: "Inscription was successfully destroyed."
    end
  end

  private

  def set_inscription
    @inscription = Inscription.find(params[:id])
  end

  def inscription_params
    params.require(:inscription).permit(:id)
  end
end

app/views/inscriptions/show.html.erb
<div class="row">
  <div class="col-6">
    <div class="inscription-overview text-center">
      <div class="container align vertical">
        <div class="mono-title">
          Course
        </div>

        <div class="main-title">
          <%= @inscription.course_name %>
        </div>

        <div class="mono-subtitle__alt">
          <%= @inscription.sections.keys.count %> Modules
        </div>

        <div class="inscription-text">
          <%= @inscription.course_description %>
        </div>

        <div class="inscription-text">
          <div class="mono-title">
            Objectives
          </div>
          <ul>
            <% @inscription.course_objectives.each do |objective| %>
              <li> <%= objective %></li>
            <% end %>
          </ul>
        </div>

        <div>
          <%= link_to 'Start', edit_inscription_path(@inscription), class:'button-alt' %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-6">
    <div class="container">
      <% @inscription.sections.each do |section_id, section| %>
        <div class="inscription-overview__module text-center">
          <div class="dark-title">
            <%= section["title"] %>
          </div>
          <div class="inscription-overview__module-stats">
            <div class="inscription-overview__module-indicator">
              <div>
                Resources
              </div>
              <div class="mono-subtitle">
                <%= section["resources"].count %>
              </div>
            </div>

            <div class="inscription-overview__module-indicator">
              <div>
                Activities
              </div>
              <div class="mono-subtitle">
                <%= section["activities"].count %>
              </div>
            </div>

            <div class="inscription-overview__module-indicator">
              <div>
                Exam
              </div>
              <div class="mono-subtitle">
                <%= section["exam"]["score"] %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>